name: Create Pull request (main)

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        required: true
        description: Target branch
        options:
          - main
      message:
        type: string
        required: true
        description: Message
        default: 'Great work!!'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Create Pull request
        run: |
          gh pr create \
            --assignee ${{ github.actor }} \
            --base ${{ github.event.inputs.target }} \
            --head develop \
            --title "Relase ($(date '+%Y/%m/%d'))" \
            --body '${{ github.event.inputs.message }}' \
            --label enhancement
